apiVersion: apps/v1
kind: Deployment
metadata:
  name: landing-app
  labels:
    app: landing-app
spec:
  selector:
    matchLabels:
      app: landing-app
  replicas: 1
  template:
    metadata:
      labels:
        app: landing-app
    spec:
      containers:
      - name: landing-app
        image: agambewe/landing-page:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 80

---

apiVersion: v1
kind: Service
metadata:
  name: landing-service
spec:
  type: NodePort
  selector:
    app: landing-app
  ports:
  - port: 80 
    protocol: "TCP"
